### ISSUE TITLE
switching table loses QR code on receipt

### ISSUE THREAD

**Issue by ERP-FTW** [ERP-FTW/mlr_pos_btcpay#1]
When the BTCpay server payment line is added and the request sent the QR code is shown on the receipt, however when navigating back to the table map and then re-opening the order the QR code is no longer shown on the receipt.

**Comment by ERP-FTW** [comment]
Thought bringing this together would solve issue but doesn't see to.
![image](https://github.com/ERP-FTW/mlr_pos_btcpay/assets/124227412/a91a09f4-4fa9-42d1-aee3-9cfcf1f808fa)


![image](https://github.com/ERP-FTW/mlr_pos_btcpay/assets/124227412/4052a91b-0704-4c0e-99b3-81cdde8e4091)
![image](https://github.com/ERP-FTW/mlr_pos_btcpay/assets/124227412/aa5d8a33-0654-4c08-b1bf-7a77fac8f8bd)

**Comment by Sagars209** [comment]
working on this

**Comment by ERP-FTW** [comment]
Sagar fixed with these sections of code
python
![image](https://github.com/ERP-FTW/mlr_pos_btcpay/assets/124227412/2fc20527-3e81-4a6e-a30e-16ed802d8c3c)
javascript
![image](https://github.com/ERP-FTW/mlr_pos_btcpay/assets/124227412/cb34b6e8-2f04-4365-91f8-218f0c75c989)
