### ISSUE TITLE
validate button is not enabled

### ISSUE THREAD

**Issue by ERP-FTW** [ERP-FTW/mlr_pos_btcpay#4]
force validation is not included and validation occurs by the timer.

**Comment by Sagars209** [comment]
currently once the payment is successful it automatically redirects to order receipt, need to the validate button enable criteria.  since there is fundamental change between v16 and v17 on how templates gets the parameters that might be causing this issue

**Comment by ERP-FTW** [comment]
still ongoing, tried with both of these options without a change

![image](https://github.com/ERP-FTW/mlr_pos_btcpay/assets/124227412/14522686-3c95-4245-8971-eb13cbce36bb)

**Comment by ERP-FTW** [comment]
Sagar fixed with js and xml
